<?php

declare(strict_types=1);

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $pageTitle
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#657187">
    <title><?= $this->section('title', 'mobiCMS') ?></title>
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <style>
        body {
            padding-top: 54px
        }

        h3 a {
            color: #657187;
            text-decoration: none
        }

        .app {
            min-height: 100vh
        }

        .bg-darka {
            background-color: #4E5869
        }
    </style>
</head>
<body class="app">
<header class="app-header">
    <nav class="navbar navbar-expand-sm navbar-dark bg-darka fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Brand -->
                <a class="navbar-brand" href="/">
                    <img src="mobicms-logo.png" alt="mobiCMS" height="28"/>
                </a>
            </div>
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="https://github.com/mobicms/" target="_blank" class="nav-link">
                            <i class="bi bi-github"></i> Contribute
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="app-content">
    <main class="container">
        <?= $this->section('content') ?>
    </main>
</div>
</body>
</html>
