<?php

/**
 * @var Mobicms\Render\Template\Template $this
 */
$this->layout('layouts::default', ['title' => '404 Not Found']);
?>
<div class="text-center">
    <h1 class="display-1 fw-bold text-danger" style="margin-top: 1em">404</h1>
    <p class="fs-3"><span class="text-danger">Opps!</span> Page not found.</p>
    <p class="lead">
        The page you’re looking for doesn’t exist.
    </p>
    <a href="/" class="btn btn-primary">Go Home</a>
</div>
