<?php

$this->layout('layout::default', ['title' => 'Home']);
$notUsed = '<span class="badge rounded-pill bg-warning text-dark">DOES NOT EXIST</span>';
?>

<div class="alert alert-primary">
    <h1><span style="color: green">mobiCMS</span> Debug Module</h1>
    <p>
        This module used exclusively during the development process
        and contains various useful and debugging information.<br>
        <strong>Do not use in living systems, or protect access with a password!</strong>
    </p>
</div>

<div class="row">
    <div class="col-md-4 p-4">
        <h3><i class="bi-info-circle-fill"></i> System Information</h3>
        <ul>
            <li><strong>OS:</strong> <?= php_uname('v') ?></li>
            <li><strong>WEB Server:</strong> <?= $webServer ?></li>
            <li><strong>PHP Version:</strong> <?= phpversion() ?></li>
            <li>
                <strong>PHP Extensions:</strong>
                <ul>
                    <?php $extensions = ['gd', 'mbstring', 'pdo'] ?>
                    <?php foreach ($extensions as $extension): ?>
                        <li>
                            <?= (
                            extension_loaded($extension)
                                ? '<span class="badge rounded-pill bg-success">YES</span>'
                                : '<span class="badge rounded-pill bg-danger">NO</span>'
                            ) . ' ' . $extension ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        </ul>
    </div>

    <div class="col-md-4 p-4">
        <h3><i class="bi bi-broadcast"></i> Client IP and UserAgent</h3>
        <ul>
            <li><strong>IP:</strong> <?= $ip ?></li>
            <li><strong>IP via Proxy:</strong> <?= $ipViaProxy ?></li>
            <li><strong>UserAgent:</strong> <?= $userAgent ?></li>
        </ul>
    </div>

    <div class="col-md-4 p-4">
        <h3><i class="bi-server"></i> Example Database</h3>
        <?php if (! empty($pdoDemo)): ?>
            <ul>
                <?php foreach ($pdoDemo as $demo): ?>
                    <li><?= $demo ?></li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <?= $notUsed ?>
        <?php endif; ?>
    </div>
</div>

<div class="row">
    <div class="col p-4">
        <h3><i class="bi-stack"></i> Request Attributes</h3>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Key</th>
                <th scope="col">Value</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($psrattributes as $key => $val): ?>
                <tr>
                    <th scope="row"><?= $key ?></th>
                    <td><?= $val ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
